#!/usr/bin/env python

import sys
import optparse
import random

import serial

def main(args):
	p = optparse.OptionParser(option_list=[
		optparse.Option('-b', '--baudrate', type=int, default=115200),
		optparse.Option('-d', '--device', default='/dev/ttyUSB0'),
		optparse.Option('--bytesize', type=int, default=8),
		optparse.Option('--stopbits', type=int, default=1),
		optparse.Option('--timeout', type=float, default=3.0),
		])
	(options, args) = p.parse_args(args)

	s = serial.Serial(options.device,
			bytesize=options.bytesize, baudrate=options.baudrate, stopbits=options.stopbits,
			timeout=options.timeout)

	while 1:
		x = random.randrange(0, 256)
		s.write(chr(x))

if __name__ == '__main__':
	main(sys.argv[1:])
